//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseStudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.studentcourseregistrations = new HashSet<studentcourseregistration>();
        }


        public int id { get; set; }

        [DisplayName("First Name")]
        public string firstname { get; set; }

        [DisplayName("Surname")]
        public string surname { get; set; }

        [DisplayName("Gender")]
        public string gender { get; set; }

        [DisplayName("Date Of Birth")]

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> dateofbirth { get; set; }

        [DisplayName("Address1")]
        public string address1 { get; set; }

        [DisplayName("Address2")]
        public string address2 { get; set; }

        [DisplayName("Address3")]
        public string address3 { get; set; }
        public int noofcourse { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentcourseregistration> studentcourseregistrations { get; set; }
    }
}
