//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseStudentManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class studentcourseregistration
    {
        public int id { get; set; }

        [DisplayName("Student")]
        public int student_id { get; set; }

        [DisplayName("Course")]
        public int course_id { get; set; }

        public virtual course course { get; set; }
        public virtual student student { get; set; }
    }
}
